//vendors action types

export const FETCH_VENDORS_START = 'FETCH_VENDORS_START';

export const FETCH_VENDORS_SUCCESS = 'FETCH_VENDORS_SUCCESS';

export const FETCH_VENDORS_FAIL = 'FETCH_VENDORS_FAIL';